version: '2'

services:
  postgres:
    image: postgres:9.6.2-alpine
    restart: always
    environment: &pg_env
      POSTGRES_USER: 'wust'
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 'wust'
  db-migration:
    image: woost/wust2.db-migration
    environment:
      <<: *pg_env
  wust:
    image: woost/wust2
    restart: always
    environment:
      <<: *pg_env
      POSTGRES_HOSTNAME: "postgres"
      WUST_AUTH_SECRET: ${WUST_AUTH_SECRET}
      WUST_EMAIL_ADDRESS: ${WUST_EMAIL_ADDRESS}
      WUST_SMTP_ENDPOINT: ${WUST_SMTP_ENDPOINT}
      WUST_SMTP_USER: ${WUST_SMTP_USER}
      WUST_SMTP_PASS: ${WUST_SMTP_PASS}
  nginx:
    image: woost/wust2.nginx
    restart: always
    volumes:
      - ${CERT_DIR}:/tls_certs/:ro
  nginx-http:
    image: woost/wust2.nginx:http
    restart: always
